name: Excel Row Count

on:
  workflow_dispatch:
    inputs:
      excel_file:
        description: "Excel file"
        required: true
      sheet_name:
        description: "Sheet name"
        required: true
      column_name:
        description: "Column name"
        required: true
      column_name2:
        description: "Column name"
        required: true
      column_name3:
        description: "Column name"
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install pandas openpyxl

      - name: Count rows
        run: |
          python <<EOF
          import pandas as pd

          file = "${{ github.event.inputs.excel_file }}"
          sheet = "${{ github.event.inputs.sheet_name }}"
          column1 = "${{ github.event.inputs.column_name }}"
          column2 = "${{ github.event.inputs.column_name2 }}"
          column3 = "${{ github.event.inputs.column_name3 }}"
          
          

          df = pd.read_excel(file, sheet_name=sheet)

          count1 = df[column1].count()
          count2 = df[column2].count()
          count3 = df[column3].count()

         
          print(f"Count1={count1}")
          print(f"Count2={count2}")
          print(f"Count3={count3}")
      
          if count1 == count2 == count3:
              print("OK - Counts match")
          else:
              print("KO - Counts do not match")
              raise SystemExit(1)
          EOF
