name: Generate Code From Input

on:
  workflow_dispatch:
    inputs:
      language:
        description: "Choose a language"
        required: true
        default: "python"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Code
        run: |
          if [ "${{ inputs.language }}" = "python" ]; then
            echo 'print("Hello from Python")' > app.py
            cat app.py

          elif [ "${{ inputs.language }}" = "java" ]; then
            echo 'System.out.print("Hello from Java");' > app.java
            cat app.java

          else
            echo "Unsupported language"
            exit 1
          fi
