name: ok-ko

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Output
        run: |
          RESULT="KO"

          if [ "$RESULT" != "OK" ]; then
            echo "ERROR: Result is not OK"
            exit 1
          fi

          exit 0
