name: Input Demo

on:
  workflow_dispatch:
    inputs:
      result:
        description: "Enter OK or KO"
        required: true
        default: "OK"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Input
        run: |
          if [ "${{ inputs.result }}" != "OK" ]; then
            echo "ERROR: Result is not OK"
            exit 1
          fi

          exit 0
