name: Table Row Counts Final

on:
  workflow_dispatch:
   inputs:
      file_to_process:
        description: 'Select the file to process'
        type: choice
        required: true
        options:
          - DEV.txt
         
   
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compare table row counts
        working-directory: ${{ github.workspace }}
        run: |
          PREV_CNT=""

          while read -r TABLE || ["$TABLE" ]; do

            echo "Checking table: $TABLE"
           
            QUERY="SELECT COUNT(*) AS COUNT_ROWS FROM $TABLE"
            echo "$QUERY"

            # run the query at some point and store the result in variable CNT
            
            CNT=100

            echo "Row Count = $CNT"

            if [ -n "$PREV_CNT" ] && [ "$CNT" != "$PREV_CNT" ]; then
              echo "KO - Table $TABLE has a different number of records."
              echo "Previous Count: $PREV_CNT"
              echo "Current Count : $CNT"
              exit 1
            fi

            PREV_CNT="$CNT"

          done < ${{ inputs.file_to_process }}

          echo "OK - All tables have matching row counts."
